### ISSUE TITLE
Importing epydemiology causes deprecation warning

### ISSUE THREAD

**Issue by lvphj** [lvphj/epydemiology#6]
When importing epydemiology into a project, a deprecation warning is generated:

```
/Users/phil/Documents/python_projects/general_python34_projects/env34/lib/python3.4/importlib/_bootstrap.py:321: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  return f(*args, **kwds)

```
Need to address.

**Comment by lvphj** [comment]
This may be a statsmodels issue.

**Comment by lvphj** [comment]
This issue no longer seems to occur when importing epydemiology into a conda environment using Python 3.7. Leave issue open for now.

**Comment by phjones-siu** [comment]
When loading epydemiology in a conda environment with Anaconda 1.6.2, Python 3.6.1 and Statsmodels 0.8.0, get the following deprecation warning:

`C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.`

Solution is likely to be to upgrade Statsmodels - assuming that is possible.
