### ISSUE TITLE
Request new function to identify repeating strings in text variable

### ISSUE THREAD

**Issue by phjones-siu** [lvphj/epydemiology#61]
In an unusual scenario, data had been provided in a way that cause data in a dataframe column to by duplicated. For example, the dataframe column might consist of data in the following format:
`Category 1: This is some text This is some text`

The function required should remove the prefix (and suffix, if present) and return the repeating string, stripped of white space at start and finish where necessary. In this example, the repeating string is `' This is some text'` (notice the leading space) and the string that should be returned should be `'This is some text'`.

**Comment by lvphj** [comment]
Added phjAddColumnOfMinRepeatingString() function to ExtrRepeatStr branch.
